name: CI
on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - master
      - main

jobs:

  lint:
    name: runner / build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest


  tests:
    name: runner / tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Unit Tests
        run: "make test"
